name: rare
base: core24
version: '1.12.0'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: Open source alternative for Epic Games Launcher, using Legendary
description: |
 Rare is a frontend for legendary-gl, an open source alternative for the Epic Games Launcher.

  Why Rare?

      Tries to be as lightweight as we can make it while still offering a feature-full experience
      Supports all major platforms (Windows, Linux, Mac)
      Gets out of your way when you don't need it, allowing you to enjoy your games

  Rare supports all core features from the Epic Games Launcher, like installing and launching games, also many options to launch games with compatibility tools.
grade: stable
confinement: strict
icon: Rare.svg

apps:
  rare:
    command-chain: [define-variables]
    command: Rare-1.12.0.0/Rare.bin
    desktop: rare.desktop
    common-id: io.github.dummerle.rare
    environment:
      HOME: $SNAP_USER_COMMON
      PATH: $SNAP/opt/wine-stable/bin:$SNAP/winehq/usr/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/winehq/usr/lib/i386-linux-gnu:$SNAP/winehq/usr/lib/i386-linux-gnu/pulseaudio:$SNAP/winehq/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      LD_PRELOAD: $SNAP/usr/lib/mangohud/lib64/libMangoHud_shim.so
    extensions: [kde-neon-6]
    plugs:
      - network-status
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - system-observe
      - hardware-observe
      - upower-observe

plugs:
  shared-memory:
    private: true
  winehq:
    content: winehq
    interface: content
    target: $SNAP/winehq
    default-provider: wine-kyu

layout:
  /opt/wine-stable:
    symlink: $SNAP/winehq/opt/wine-stable
  /usr/lib/i386-linux-gnu/alsa-lib:
    symlink: $SNAP/winehq/usr/lib/i386-linux-gnu/alsa-lib
  /usr/lib/x86_64-linux-gnu/alsa-lib:
    symlink: $SNAP/winehq/usr/lib/x86_64-linux-gnu/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/winehq/usr/share/alsa
  /usr/lib/mangohud:
    symlink: $SNAP/usr/lib/mangohud

lint:
  ignore:
    - library:
        - usr/lib/mangohud/lib32/**

parts:
  rare-app:
    plugin: dump
    source: https://github.com/RareDevs/Rare/releases/download/1.12.0/Rare-1.12.0.0-linux.zip

  base-dependencies:
    after: [rare-app]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libdecor-0-0
    prime:
      - usr/lib/x86_64-linux-gnu/libSDL2-2.0.so*
      - usr/lib/x86_64-linux-gnu/libdecor-0.so*

  command-chain:
    after: [base-dependencies]
    plugin: dump
    source: ./other-files

  desktop-file:
    after: [command-chain]
    plugin: nil
    build-packages: [curl]
    override-build: |
      curl -o $CRAFT_PART_INSTALL/rare.desktop https://raw.githubusercontent.com/RareDevs/Rare/refs/heads/main/misc/rare.desktop
      sed -i 's|Name=Rare|Name=Rare [Kyu]|' $CRAFT_PART_INSTALL/rare.desktop

  mangohud:
    after: [desktop-file]
    plugin: dump
    source: https://github.com/flightlessmango/MangoHud/releases/download/v0.8.2/MangoHud-0.8.2.r0.ga37b007.tar.gz
    override-build: |
      craftctl default
      tar -xvf MangoHud-package.tar -C $CRAFT_PART_INSTALL
    prime: [usr]
