#!/bin/bash

export XDG_CONFIG_HOME="$SNAP_USER_COMMON/.config"
export XDG_DATA_HOME="$SNAP_USER_COMMON/.local/share"

mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_DATA_HOME"

# Create a Desktop link in $SNAP_USER_COMMON that opens the user's actual desktop folder.
DESKTOP_PATH=$(grep "XDG_DESKTOP_DIR" $SNAP_REAL_HOME/.config/user-dirs.dirs | cut -d'=' -f2 | sed 's/"//g' | sed "s#\$HOME#$SNAP_REAL_HOME#g")
rm -rf $SNAP_USER_COMMON/Desktop
ln -snf "$DESKTOP_PATH" "$SNAP_USER_COMMON/Desktop"

if snapctl is-connected home; then
    export UMU_FOLDERS_PATH="$SNAP_REAL_HOME/App/UMU"
else
    export UMU_FOLDERS_PATH="$SNAP_USER_COMMON/App/UMU"
fi

exec "$@"
